# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KbnCli < Formula
  desc "Obsidian vault kanban board TUI viewer"
  homepage "https://github.com/anyjava/kbn-cli"
  version "0.1.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.4/kbn_0.1.4_darwin_amd64.tar.gz"
      sha256 "c314e18cad2b5c843c2d615c5f1fb35b758172e3f31b9a46ac3192cf921f0b40"

      define_method(:install) do
        bin.install "kbn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.4/kbn_0.1.4_darwin_arm64.tar.gz"
      sha256 "f654e94e5aacb39ea06ea45fa1d7f5242cf75d75f146c67a2814ff9b6090e95a"

      define_method(:install) do
        bin.install "kbn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.4/kbn_0.1.4_linux_amd64.tar.gz"
      sha256 "4002604a33bb3cf667e5a66211ab2eb959a679780deebe7b3909815ee3056cca"
      define_method(:install) do
        bin.install "kbn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.4/kbn_0.1.4_linux_arm64.tar.gz"
      sha256 "5c7a0f6d7540b627a4350bbe370248dceb5eaea40664ca62cf6d2714a37aeb65"
      define_method(:install) do
        bin.install "kbn"
      end
    end
  end
end
