# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kbn < Formula
  desc "Obsidian vault kanban board TUI viewer"
  homepage "https://github.com/anyjava/kbn-cli"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.1/kbn_0.1.1_darwin_amd64.tar.gz"
      sha256 "ca8e3f52dfcb32ebadaaaaced1ecd4bffe7d08552d4033760ad16169e1a16151"

      define_method(:install) do
        bin.install "kbn"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.1/kbn_0.1.1_darwin_arm64.tar.gz"
      sha256 "4c604eed3a9997c9dfbbd5c28c93caef6b99e4b955f64ddd20fe0449d30124d8"

      define_method(:install) do
        bin.install "kbn"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.1/kbn_0.1.1_linux_amd64.tar.gz"
      sha256 "556ac934ad3901cfecefafaeaf5bd54c48f2823411f4d07e55e72beec8200f7c"
      define_method(:install) do
        bin.install "kbn"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/anyjava/kbn-cli/releases/download/v0.1.1/kbn_0.1.1_linux_arm64.tar.gz"
      sha256 "da11c420871b98d04b4245d667c67c877ee53db3c35ee6113c0d361ea917bf7a"
      define_method(:install) do
        bin.install "kbn"
      end
    end
  end
end
